export const MIME_TYPES: Record<string, string> = {
	// Images
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.png': 'image/png',
	'.gif': 'image/gif',
	'.webp': 'image/webp',
	'.avif': 'image/avif',
	'.svg': 'image/svg+xml',
	'.ico': 'image/x-icon',
	'.bmp': 'image/bmp',
	'.tiff': 'image/tiff',
	'.tif': 'image/tiff',
	'.heic': 'image/heic',
	'.heif': 'image/heif',
	'.jxl': 'image/jxl',
	'.psd': 'image/vnd.adobe.photoshop',
	'.ai': 'application/postscript',
	'.eps': 'application/postscript',
	'.raw': 'image/x-raw',
	'.cr2': 'image/x-canon-cr2',
	'.nef': 'image/x-nikon-nef',
	'.arw': 'image/x-sony-arw',

	// Fonts
	'.woff': 'font/woff',
	'.woff2': 'font/woff2',
	'.ttf': 'font/ttf',
	'.eot': 'application/vnd.ms-fontobject',
	'.otf': 'font/otf',

	// Web Assets
	'.css': 'text/css',
	'.js': 'application/javascript',
	'.mjs': 'application/javascript',
	'.jsx': 'text/jsx',
	'.ts': 'application/typescript',
	'.tsx': 'text/tsx',
	'.json': 'application/json',
	'.xml': 'application/xml',
	'.html': 'text/html',
	'.htm': 'text/html',
	'.xhtml': 'application/xhtml+xml',
	'.txt': 'text/plain',
	'.md': 'text/markdown',
	'.markdown': 'text/markdown',
	'.csv': 'text/csv',
	'.yaml': 'application/x-yaml',
	'.yml': 'application/x-yaml',
	'.toml': 'application/toml',

	// Documents
	'.pdf': 'application/pdf',
	'.doc': 'application/msword',
	'.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'.xls': 'application/vnd.ms-excel',
	'.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'.ppt': 'application/vnd.ms-powerpoint',
	'.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'.odt': 'application/vnd.oasis.opendocument.text',
	'.ods': 'application/vnd.oasis.opendocument.spreadsheet',
	'.odp': 'application/vnd.oasis.opendocument.presentation',
	'.rtf': 'application/rtf',
	'.tex': 'application/x-tex',
	'.latex': 'application/x-latex',

	// Audio
	'.mp3': 'audio/mpeg',
	'.wav': 'audio/wav',
	'.flac': 'audio/flac',
	'.aac': 'audio/aac',
	'.ogg': 'audio/ogg',
	'.oga': 'audio/ogg',
	'.opus': 'audio/opus',
	'.m4a': 'audio/mp4',
	'.wma': 'audio/x-ms-wma',
	'.aiff': 'audio/aiff',
	'.au': 'audio/basic',
	'.mid': 'audio/midi',
	'.midi': 'audio/midi',

	// Video
	'.mp4': 'video/mp4',
	'.webm': 'video/webm',
	'.avi': 'video/x-msvideo',
	'.mov': 'video/quicktime',
	'.wmv': 'video/x-ms-wmv',
	'.flv': 'video/x-flv',
	'.mkv': 'video/x-matroska',
	'.m4v': 'video/x-m4v',
	'.3gp': 'video/3gpp',
	'.ogv': 'video/ogg',
	'.mts': 'video/mp2t',
	'.m2ts': 'video/mp2t',
	'.vob': 'video/mpeg',
	'.asf': 'video/x-ms-asf',
	'.rm': 'application/vnd.rn-realmedia',
	'.rmvb': 'application/vnd.rn-realmedia-vbr',

	// Archives
	'.zip': 'application/zip',
	'.gz': 'application/gzip',
	'.tar': 'application/x-tar',
	'.rar': 'application/vnd.rar',
	'.7z': 'application/x-7z-compressed',
	'.bz2': 'application/x-bzip2',
	'.xz': 'application/x-xz',
	'.lzma': 'application/x-lzma',
	'.cab': 'application/vnd.ms-cab-compressed',
	'.iso': 'application/x-iso9660-image',
	'.dmg': 'application/x-apple-diskimage',

	// Executables
	'.exe': 'application/x-msdownload',
	'.msi': 'application/x-msi',
	'.deb': 'application/vnd.debian.binary-package',
	'.rpm': 'application/x-rpm',
	'.pkg': 'application/vnd.apple.installer+xml',
	'.apk': 'application/vnd.android.package-archive',

	// 3D & CAD
	'.obj': 'text/plain',
	'.fbx': 'application/octet-stream',
	'.dae': 'model/vnd.collada+xml',
	'.3ds': 'application/x-3ds',
	'.max': 'application/x-3dsmax',
	'.blend': 'application/x-blender',
	'.stl': 'application/sla',
	'.ply': 'application/octet-stream',
	'.wrl': 'model/vrml',
	'.x3d': 'model/x3d+xml',

	// Database
	'.sql': 'application/sql',
	'.db': 'application/x-sqlite3',
	'.sqlite': 'application/x-sqlite3',
	'.sqlite3': 'application/x-sqlite3',

	// Configuration
	'.ini': 'text/plain',
	'.conf': 'text/plain',
	'.config': 'text/plain',
	'.env': 'text/plain',
	'.properties': 'text/plain',
	'.cfg': 'text/plain',

	// Logs
	'.log': 'text/plain',
	'.out': 'text/plain',
	'.err': 'text/plain',

	// Certificates
	'.pem': 'application/x-pem-file',
	'.crt': 'application/x-x509-ca-cert',
	'.cer': 'application/x-x509-ca-cert',
	'.der': 'application/x-x509-ca-cert',
	'.p12': 'application/x-pkcs12',
	'.pfx': 'application/x-pkcs12',
	'.key': 'application/x-pem-file',

	// Other
	'.swf': 'application/x-shockwave-flash',
	'.jar': 'application/java-archive',
	'.war': 'application/java-archive',
	'.ear': 'application/java-archive',
	'.class': 'application/java-vm',
	'.py': 'text/x-python',
	'.php': 'application/x-httpd-php',
	'.rb': 'text/x-ruby',
	'.pl': 'text/x-perl',
	'.sh': 'application/x-sh',
	'.bat': 'application/x-msdos-program',
	'.cmd': 'application/x-msdos-program',
	'.ps1': 'application/x-powershell',
	'.vbs': 'text/vbscript',
	'.lua': 'text/x-lua',
	'.go': 'text/x-go',
	'.rs': 'text/x-rust',
	'.cpp': 'text/x-c++src',
	'.c': 'text/x-csrc',
	'.h': 'text/x-chdr',
	'.java': 'text/x-java-source',
	'.scala': 'text/x-scala',
	'.kt': 'text/x-kotlin',
	'.swift': 'text/x-swift',
	'.m': 'text/x-objective-c',
	'.mm': 'text/x-objective-c++',
	'.r': 'text/x-r',
	'.mat': 'application/x-matlab-data',
	'.sas': 'text/x-sas',
	'.spss': 'application/x-spss',
	'.stata': 'application/x-stata',
	'.rdata': 'application/x-r-data',
	'.rds': 'application/x-r-data',
	'.rda': 'application/x-r-data',
};

export const CACHE_TTL = {
	STATIC_ASSETS: 31536000, // 1 year for static assets
	IMAGES: 2592000,         // 30 days for images
	FONTS: 31536000,         // 1 year for fonts
	STYLESHEETS: 86400,      // 1 day for CSS
	SCRIPTS: 86400,          // 1 day for JS
	DOCUMENTS: 3600,         // 1 hour for HTML/documents
	DEFAULT: 3600            // 1 hour default
};